import type { Metadata } from "next";
import Link from "next/link";
import "../terms.css";
import { BrandLogo } from "../../brand-logo";

export const metadata: Metadata = {
 title: "Terms & Conditions · Irkanti",
 description: "Irkanti account, bidding and payment terms, including deposits, payment deadlines and property transactions.",
 alternates: { canonical: "https://irkanti.com/terms/2026-09-22" },
};

// Preserve this version after publication. Do not change the text behind existing consent records.
export default function TermsPage() {
 return <div className="termsPage">
  <header className="termsHeader"><Link className="brand" href="/" aria-label="Irkanti home"><BrandLogo eager /></Link><a href="/account">Account</a></header>
  <main className="termsContent">
   <p className="termsEyebrow">VERSION 2026-09-22 · 22 SEPTEMBER 2026</p>
   <h1>Terms & Conditions</h1>
   <p className="termsIntro">Please read these terms before completing your account or placing a bid. A winning bid in a live auction carries a payment commitment, subject to the protections and exceptions below.</p>
   <section className="termsPayment" aria-labelledby="payment-summary">
    <h2 id="payment-summary">Your winning-bid commitment</h2>
    <div><p><strong>10% deposit</strong><span>Due on the calendar day the auction closes.</span></p><p><strong>Full payment within 30 days</strong><span>The deposit counts towards the price, not on top of it.</span></p></div>
    <p>Deadlines use Malta local time (Europe/Malta). Property follows a separate notarial process. Statutory consumer rights are not waived.</p>
   </section>
   <nav aria-label="Terms contents"><a href="#operator">Operator</a><a href="#accounts">Accounts</a><a href="#bidding">Bidding</a><a href="#payments">Payments</a><a href="#property">Property</a><a href="#consumer-rights">Consumer rights</a><a href="#disputes">Complaints</a></nav>
   <section id="operator"><h2>1. Who operates Irkanti</h2><p>Irkanti is operated by Luca Arrigo, Ogirra, Triq Il Kaffis, Swieqi, Malta. Correspondence concerning these terms may be sent to this address.</p><p>Irkanti provides a marketplace for sellers and buyers. Unless a listing expressly identifies Irkanti as the seller, the asset is offered by the seller identified in that listing. Seller identity, trader or private-seller status, item details and applicable charges must be disclosed before a live bid is accepted.</p></section>
   <section id="accounts"><h2>2. Accounts and verification</h2><p>You must be at least 18, have capacity to enter into the transaction and provide accurate information. If acting for a business or another person, you must have authority to do so. Keep your sign-in details secure and report suspected unauthorised use promptly.</p><p>Buyer and seller onboarding are separate. Email confirmation, document upload and staff approval are different steps. Uploading a document does not itself approve an account. Verification documents are private and available to the account holder and authorised staff, not other members.</p><p>By selecting the agreement checkbox and continuing, you confirm you have read and agree to this version. We record your account, account type, the terms version and acceptance time. Registration alone does not create an obligation to buy an item.</p></section>
   <section id="bidding"><h2>3. Bidding and sale formation</h2><p>Review the description, condition, photographs, viewing arrangements, fees and any lot-specific terms before bidding. Ask for clarification if anything is unclear. Sellers must describe assets honestly, disclose material defects and have the right to sell them.</p><p>A submitted bid is an offer to buy. Your maximum bid authorises bidding up to that amount; it is not necessarily the final sale price. A live sale is formed when the auction closes and the platform confirms your bid as the winning bid, provided any reserve and stated sale conditions have been met. Property is subject to section 5.</p><p>Unsuccessful bids, reserve-not-met results and clearly identified fictional or test listings do not create purchase obligations. An upload or onboarding checkbox does not convert a test listing into a real sale. Do not bid on your own assets, including through another account, or coordinate bids to manipulate prices.</p><p>The server-recorded closing time governs, including any anti-sniping extension. A screen display, interrupted connection or unconfirmed submission is not proof that a bid was accepted. Report suspected errors promptly; any correction must respect applicable law and existing parties’ rights.</p></section>
   <section id="payments"><h2>4. Deposit, balance and payment responsibility</h2><p>For a valid winning bid in a live auction, you agree to be legally responsible for paying a deposit equal to <strong>10% of the final winning price on the day the auction closes</strong>, by 23:59 Malta local time. You must pay the remaining 90%, together with any separately disclosed buyer fees, taxes and agreed delivery charges, <strong>within 30 calendar days after the closing date</strong>, by 23:59 Malta local time on that date.</p><p>The deposit is part-payment and is credited in full against the winning price. For example, a €10,000 winning price requires a €1,000 deposit and a €9,000 balance, plus only the applicable charges disclosed before bidding. Your unused maximum bid is not the deposit basis.</p><p>Check that you can meet these deadlines before bidding. Financing difficulties do not automatically extend them. Use only verified payment instructions associated with your order; do not send money in response to an unsolicited message. Payment handling is not represented as an escrow service.</p><p>If payment is late, the seller or operator may contact you, restrict bidding and seek performance or other remedies available under the applicable contract and law. These terms do not impose automatic deposit forfeiture, penalties or unlimited recovery costs. Any cancellation, refund or recovery of loss must respect statutory rights, proportionality and applicable law.</p><p>Payment and handover are separate. Agree collection, delivery and any required vehicle or vessel transfer documentation with the seller. Do not confirm handover before it has occurred. Nothing here authorises a charge to a payment method without the necessary payment authorisation.</p></section>
   <section id="property"><h2>5. Property requires separate legal documents</h2><p>A website bid, account acceptance or online payment does not itself transfer ownership of Maltese immovable property or replace the required legal formalities. Property transactions require a separately agreed, lawyer/notary-reviewed process, including any promise of sale, title checks and final deed.</p><p>The intended 10% deposit and 30-day timetable must be expressly agreed in the applicable property documents where lawful and practicable. Those documents govern property deposits, conditions and completion. Do not pay a property deposit through an ordinary marketplace checkout; follow the instructions agreed with your notary.</p></section>
   <section id="consumer-rights"><h2>6. Consumer rights, cancellations and refunds</h2><p>These terms do not exclude mandatory consumer protections. An online-only auction is not automatically exempt from distance-selling rules simply because bids are used. Where a trader sells to a consumer, applicable withdrawal, conformity and refund rights remain available. Private sales may have different protections.</p><p>Where the statutory withdrawal right applies to goods, the usual period is 14 days from receipt, subject to the applicable rules and exceptions. The seller must provide the required information and means to exercise that right. Contact the seller and Irkanti promptly if you wish to cancel or if an item is missing, damaged or materially different from its description. A deposit is not automatically non-refundable.</p></section>
   <section id="disputes"><h2>7. Complaints and disputes</h2><p>Include your account email, listing or order reference, a description of the issue and the outcome you seek when contacting the operator at the address above. Do not send identity documents or payment-card details in ordinary correspondence. You may also seek assistance from the <a href="https://mccaa.org.mt/" target="_blank" rel="noopener noreferrer">Malta Competition and Consumer Affairs Authority</a>, where relevant.</p><p>Maltese law applies, without depriving consumers of mandatory protections or rights to bring proceedings in courts available under applicable law. Nothing limits liability or legal remedies that cannot lawfully be limited.</p></section>
   <section><h2>8. Changes to these terms</h2><p>Material changes will be published as a new version and require fresh acceptance where applicable. New terms do not retrospectively change a concluded sale or turn earlier account activity into acceptance. Keep a copy of the version you agree to and the terms of the particular lot.</p></section>
   <p className="termsReturn"><a href="/account">Return to your account</a></p>
  </main>
  <footer className="termsFooter"><Link className="brand" href="/" aria-label="Irkanti home"><BrandLogo /></Link><p>Malta · <Link href="/">Marketplace</Link></p></footer>
 </div>;
}
